version: "3"
services:
  gitlab:
    image: gitlab/gitlab-ce:11.8.0-ce.0
    restart: always
    hostname: "gitlab.codeforfun.cn"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.codeforfun.cn:3000'
        nginx['redirect_http_to_https'] = false
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    ports:
      - "3000:3000"
      - "2222:22"
    volumes:
      - './docker/gitlab/config:/etc/gitlab'
      - './docker/gitlab/logs:/var/log/gitlab'
      - './docker/gitlab/data:/var/opt/gitlab'
  gitlab-runner:
    image: registry.cn-beijing.aliyuncs.com/wangdali/gitlab-runner:alpine
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./docker/gitlab-runner:/etc/gitlab-runner"
